#r @"bin\Debug\Hopac.Core.dll"
#r @"bin\Debug\Hopac.dll" 
#r @"bin\Debug\Hopac.Platform.dll"
//#r @"packages\Hopac.0.0.0.33\lib\net45\Hopac.Core.dll"
//#r @"packages\Hopac.0.0.0.33\lib\net45\Hopac.dll"
#r "packages/ExtCore.0.8.43/lib/net40/ExtCore.dll" 
#r "System.Runtime"
#r "System.Threading.Tasks"
